version: '3'
services:
  angular_cli:
    image: trion/ng-cli:latest
    container_name: 'angular_cli'
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    command: >
      bash -c "ng new myApp --directory ./"
